< !DOCTYPE html >
<html>
<head>
<title>WorldMilitaryRanking1~10</title>
</head>
<body>

<h1>WorldMilitaryRanking1~10</h1>
<p>1.United States 2.Russia 3.China 4.India 5.United Kingdom 6.South Korea 7.Pakistan 8.Japan 9.France 10.Italy</p>

</body>
</html>
