<!DOCTYPE html>
<html>
<head>world miltary Rangking
<title>world Miltary Rangking</title>
</head>
<body>

<h1> Ranking <h1>
<p>1.usa 2.rus 3.chn 4.ind 5.ukd 6.sko 7.pak 8.jpn 9.fra 10.ita
</body>
<html>
